# General
site_name: 'Notes'
site_description: 'My notes on things.'
site_author: 'Joey Hejna'
site_url: 'http://joeyhejna.com/notes'

# Theme Configuration
theme:
  name: 'material'
  feature:
    tabs: true
  palette: 
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'code'

copyright: 'Copyright &copy; 2019 Joey Hejna'

# Social Links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/jhejna'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jhejna'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extra JS for plugins
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'